apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kip1y7m2k-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kip1y7m2k-go 
  name: kip1y7m2k-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kip1y7m2k-go 
